### ISSUE TITLE
pc terminal için parametre yükleyin

### ISSUE THREAD

**Issue by ardasdasdas** [huginsdk/fpu#15]
Kasayı iki gün önce Ethernet ile bağladığımız zaman Cihaz Parametreleri Eşleştir ve Uzaktan Yükle aşamalarında BAŞARILI olarak sonuç elde etmiştik. Hiçbir sorun olmadan çalışırken bugün kasayı açtığımızda kod ile bağlandıktan sonra kasa ekranında PC TERMİNAL İÇİN PARAMETRE YÜKLEYİN yazısı beliriyor. Kasiyerdeyken 3 + "anahtar semoblü"'ne basıp parametre yükle seçeneğini seçtiğim zaman parametre yükleme başarısız olmakta. Tekrar servis modundan Cihaz Parametreleri Eşleştir ve Uzaktan Yükle aşamalarını denediğimiz zaman BAŞARISIZ olmakta. Debug yaparak baktığımız zaman `if (!printer.Connect(connection.ToObject(), deviceInfo))` kontrolü sırasında bu PC TERMİNAL İÇİN PARAMETRE YÜKLEYİN hatası beliriyor. Kasayı fabrika ayarlarına da döndürdük yine aynı hatalarla karşılaşıyoruz. Nasıl bir çözüm uygulamalıyız?

**Comment by turgutse** [comment]
Eşleme yapılan kasalar için GMP3 parametre tanımlanması ve yüklenmesi gerekmektedir. Parametre tanımı için guncelleme@hugin.com.tr adresine kasa sicil bilgileri ile mail olarak baş vurunuz.

**Comment by ardasdasdas** [comment]
Hugin destek ile konuştum. Cihaz bir parametre yükleme işleminden sonraki 10 gün içerisinde internete bağlanmazsa PC TERMİNAL İÇİN PARAMETRE uyarısı çıkıyormuş. Cihazı internete açıp parametre yükleyince sorun çözüldü.
