### ISSUE TITLE
How can I use PrintItem function without PLUNo parameter?

### ISSUE THREAD

**Issue by ismailkocacan** [huginsdk/fpu#3]
I want to use PrintItem function with barcode parameter instead of PLUNo.
Thanks in advance

**Comment by ayhandemirhan** [comment]
Send PLUNo as zero. We suggest you use PrintDepartment functions instead of PrintItem if you don't need PLU Report. Because PrintDepartment() faster than PrintItem()

Thanks

**Comment by ismailkocacan** [comment]
Thank you reply.

I'm using PrintItem function like that and returning error.
`PrintItem(0,plu.QuantityOfProduct,plu.UnitPrice,null,plu.Barcode,-1,-1);`

> Error Code : 114
> ERR_INVALID_PLUNO
> Invalid PLU number Define PLU
> 
> Status Code : 2
> ST_SELLING

**Comment by ayhandemirhan** [comment]
Which cashier with you signed in?

**Comment by ismailkocacan** [comment]
Cashier ID is 9

**Comment by ayhandemirhan** [comment]
You have to fill full fields to sell item with cashier 9, If you wantto sell existing item sign in with cashier 6.

**Comment by ismailkocacan** [comment]
I'm signed with cashier 6. But still error.

**Comment by ayhandemirhan** [comment]
You couldn't print item with only barcode with cashier 6, You should sign witn cashier 9 and fill and send Name, deptid and the others. Why don't you use PrintDepartment() ?

**Comment by ismailkocacan** [comment]
Daha önce cihaza yüklemiş olduğumuz barkod kodlu PLU (Ürün) bilgilerini, barkod okuyucu ile okutup satış yapmak istiyoruz.

**Comment by ayhandemirhan** [comment]
Kayıtlı ürünlerin satışı sadece satış yetkili kasiyerler(kasiyer no 1..6) ile giriş yaptıktan sonra PLU no ile yapılabiliyor. Barkod üzerinden satış yapılamıyor. Manuel olarak yaptığınız kayıtın plu no sunu bilmeniz ve göndermeniz gerekmekte. 

Kasiyer 9 ile giriş yaptıktan sonra yapacağınız satışlarda ürüne ait tüm bilgileri göndermeniz gerekmekte. Çünkü ürün yazarkasada olmasa bile gelen değerlere göre üzerine kayıt edip satışı gerçekleştirme imkanı sunmaktadır. Kasiyer 9 ile satış yaparken PLU no sıfır, barkod gerçerli bir değerle set ederseniz, yazarkasa barkoda göre ürünü geçici olarak kayıt edip satışı tamamlar. ,PLU no olmadığı içinde veritabanında kayıtlı kalmaz. Kasiyer 9 ile satış yapacaksanız her zaman tüm bilgileri göndermeniz gerekmektedir.

Departman satışlarında ise, barkod okutulduktan sonra ürüne ait departman, adet, birim fiyatı, ürün adı ve tartılabilirlik opsiyonlarını göndererek satışı yapabilirsiniz. Satılan ürüne ait bilgiler veritabanına kayıt edilmez, departman satışları toplamına işlenir. Ürün raporlarının kullanılmadığı işletmeler için kullanışlı bir yöntemdir. Veritabanından ürün sorgusu yapılmadığından da daha hızlı fiş çıktısı alınız.

Sisteminiz ile ilgili detaylı bilgi verirseniz daha iyi önerilerde bulunabiliriz.

**Comment by ismailkocacan** [comment]
Ayhan bey detaylı cevap ve ilginiz için teşekkür ediyorum.
