### ISSUE TITLE
FISCAL ID

### ISSUE THREAD

**Issue by osmanergin89** [huginsdk/fpu#9]
Merhaba, FISCAL ID yi nerden bulabilirim?

**Comment by osmanergin89** [comment]
![33189426_1809081289399147_7313127942605766656_n](https://user-images.githubusercontent.com/39513611/40347943-afc392ee-5daa-11e8-919f-35602d0325c5.jpg)
![33336026_1809081259399150_6409878809675300864_n](https://user-images.githubusercontent.com/39513611/40347944-afeea894-5daa-11e8-8141-7000ed15e281.jpg)
![33385771_1809081279399148_6368413876844756992_n](https://user-images.githubusercontent.com/39513611/40347945-b0b3dd80-5daa-11e8-8bae-5c790fc31d58.jpg)

**Comment by osmanergin89** [comment]
ektede göreceğiniz gibi exeyi çalıştırıp bilgileri girdiğimde bağlanamıyorum.

**Comment by osmanergin89** [comment]
@SerdarGokcen daha önce yazar kasalar ile hiç çalışmadım. ÖKC servis modu nedir?

**Comment by SerdarGokcen** [comment]
sezer.varli@hugin.com.tr üzerinden iletişime geçer misiniz, kendisi size gerekli desteği verecektir.
